In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('AmesHousing.csv')

In [3]:
data

Order        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0         1  526301100           20        RL         141.0     31770   Pave   
1         2  526350040           20        RH          80.0     11622   Pave   
2         3  526351010           20        RL          81.0     14267   Pave   
3         4  526353030           20        RL          93.0     11160   Pave   
4         5  527105010           60        RL          74.0     13830   Pave   
...     ...        ...          ...       ...           ...       ...    ...   
2925   2926  923275080           80        RL          37.0      7937   Pave   
2926   2927  923276100           20        RL           NaN      8885   Pave   
2927   2928  923400125           85        RL          62.0     10441   Pave   
2928   2929  924100070           20        RL          77.0     10010   Pave   
2929   2930  924151050           60        RL          74.0      9627   Pave   

     Alley Lot Shape Land Contour  ... Pool Area Pool QC  Fence Misc Feature  \
0      NaN       IR1          Lvl  ...         0     NaN    NaN          NaN   
1      NaN       Reg          Lvl  ...         0     NaN  MnPrv          NaN   
2      NaN       IR1          Lvl  ...         0     NaN    NaN         Gar2   
3      NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
4      NaN       IR1          Lvl  ...         0     NaN  MnPrv          NaN   
...    ...       ...          ...  ...       ...     ...    ...          ...   
2925   NaN       IR1          Lvl  ...         0     NaN  GdPrv          NaN   
2926   NaN       IR1          Low  ...         0     NaN  MnPrv          NaN   
2927   NaN       Reg          Lvl  ...         0     NaN  MnPrv         Shed   
2928   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
2929   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   

     Misc Val Mo Sold Yr Sold Sale Type  Sale Condition  SalePrice  
0           0       5    2010       WD           Normal     215000  
1           0       6    2010       WD           Normal     105000  
2       12500       6    2010       WD           Normal     172000  
3           0       4    2010       WD           Normal     244000  
4           0       3    2010       WD           Normal     189900  
...       ...     ...     ...       ...             ...        ...  
2925        0       3    2006       WD           Normal     142500  
2926        0       6    2006       WD           Normal     131000  
2927      700       7    2006       WD           Normal     132000  
2928        0       4    2006       WD           Normal     170000  
2929        0      11    2006       WD           Normal     188000  

[2930 rows x 82 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Order            2930 non-null   int64  
 1   PID              2930 non-null   int64  
 2   MS SubClass      2930 non-null   int64  
 3   MS Zoning        2930 non-null   object 
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64  
 6   Street           2930 non-null   object 
 7   Alley            198 non-null    object 
 8   Lot Shape        2930 non-null   object 
 9   Land Contour     2930 non-null   object 
 10  Utilities        2930 non-null   object 
 11  Lot Config       2930 non-null   object 
 12  Land Slope       2930 non-null   object 
 13  Neighborhood     2930 non-null   object 
 14  Condition 1      2930 non-null   object 
 15  Condition 2      2930 non-null   object 
 16  Bldg Type        2930 non-null   object 
 17  House Style   

In [5]:
data.drop(columns=['Order','PID'],inplace=True)

In [6]:
data

MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley Lot Shape  \
0              20        RL         141.0     31770   Pave   NaN       IR1   
1              20        RH          80.0     11622   Pave   NaN       Reg   
2              20        RL          81.0     14267   Pave   NaN       IR1   
3              20        RL          93.0     11160   Pave   NaN       Reg   
4              60        RL          74.0     13830   Pave   NaN       IR1   
...           ...       ...           ...       ...    ...   ...       ...   
2925           80        RL          37.0      7937   Pave   NaN       IR1   
2926           20        RL           NaN      8885   Pave   NaN       IR1   
2927           85        RL          62.0     10441   Pave   NaN       Reg   
2928           20        RL          77.0     10010   Pave   NaN       Reg   
2929           60        RL          74.0      9627   Pave   NaN       Reg   

     Land Contour Utilities Lot Config  ... Pool Area Pool QC  Fence  \
0             Lvl    AllPub     Corner  ...         0     NaN    NaN   
1             Lvl    AllPub     Inside  ...         0     NaN  MnPrv   
2             Lvl    AllPub     Corner  ...         0     NaN    NaN   
3             Lvl    AllPub     Corner  ...         0     NaN    NaN   
4             Lvl    AllPub     Inside  ...         0     NaN  MnPrv   
...           ...       ...        ...  ...       ...     ...    ...   
2925          Lvl    AllPub    CulDSac  ...         0     NaN  GdPrv   
2926          Low    AllPub     Inside  ...         0     NaN  MnPrv   
2927          Lvl    AllPub     Inside  ...         0     NaN  MnPrv   
2928          Lvl    AllPub     Inside  ...         0     NaN    NaN   
2929          Lvl    AllPub     Inside  ...         0     NaN    NaN   

     Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  Sale Condition  \
0             NaN        0       5     2010        WD           Normal   
1             NaN        0       6     2010        WD           Normal   
2            Gar2    12500       6     2010        WD           Normal   
3             NaN        0       4     2010        WD           Normal   
4             NaN        0       3     2010        WD           Normal   
...           ...      ...     ...      ...        ...             ...   
2925          NaN        0       3     2006        WD           Normal   
2926          NaN        0       6     2006        WD           Normal   
2927         Shed      700       7     2006        WD           Normal   
2928          NaN        0       4     2006        WD           Normal   
2929          NaN        0      11     2006        WD           Normal   

      SalePrice  
0        215000  
1        105000  
2        172000  
3        244000  
4        189900  
...         ...  
2925     142500  
2926     131000  
2927     132000  
2928     170000  
2929     188000  

[2930 rows x 80 columns]

In [7]:
data.isna().sum()

MS SubClass         0
MS Zoning           0
Lot Frontage      490
Lot Area            0
Street              0
                 ... 
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 80, dtype: int64

In [8]:
num = data.select_dtypes(include=['int64','float64']).columns

In [9]:
num

Index(['MS SubClass', 'Lot Frontage', 'Lot Area', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Mas Vnr Area',
       'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area',
       'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath', 'Half Bath',
       'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd', 'Fireplaces',
       'Garage Yr Blt', 'Garage Cars', 'Garage Area', 'Wood Deck SF',
       'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch',
       'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold', 'SalePrice'],
      dtype='object')

In [10]:
cat = data.select_dtypes(include=['object']).columns

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
si = SimpleImputer(strategy='median')

In [13]:
data[num] = si.fit_transform(data[num])

In [14]:
data

MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley Lot Shape  \
0            20.0        RL         141.0   31770.0   Pave   NaN       IR1   
1            20.0        RH          80.0   11622.0   Pave   NaN       Reg   
2            20.0        RL          81.0   14267.0   Pave   NaN       IR1   
3            20.0        RL          93.0   11160.0   Pave   NaN       Reg   
4            60.0        RL          74.0   13830.0   Pave   NaN       IR1   
...           ...       ...           ...       ...    ...   ...       ...   
2925         80.0        RL          37.0    7937.0   Pave   NaN       IR1   
2926         20.0        RL          68.0    8885.0   Pave   NaN       IR1   
2927         85.0        RL          62.0   10441.0   Pave   NaN       Reg   
2928         20.0        RL          77.0   10010.0   Pave   NaN       Reg   
2929         60.0        RL          74.0    9627.0   Pave   NaN       Reg   

     Land Contour Utilities Lot Config  ... Pool Area Pool QC  Fence  \
0             Lvl    AllPub     Corner  ...       0.0     NaN    NaN   
1             Lvl    AllPub     Inside  ...       0.0     NaN  MnPrv   
2             Lvl    AllPub     Corner  ...       0.0     NaN    NaN   
3             Lvl    AllPub     Corner  ...       0.0     NaN    NaN   
4             Lvl    AllPub     Inside  ...       0.0     NaN  MnPrv   
...           ...       ...        ...  ...       ...     ...    ...   
2925          Lvl    AllPub    CulDSac  ...       0.0     NaN  GdPrv   
2926          Low    AllPub     Inside  ...       0.0     NaN  MnPrv   
2927          Lvl    AllPub     Inside  ...       0.0     NaN  MnPrv   
2928          Lvl    AllPub     Inside  ...       0.0     NaN    NaN   
2929          Lvl    AllPub     Inside  ...       0.0     NaN    NaN   

     Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  Sale Condition  \
0             NaN      0.0     5.0   2010.0        WD           Normal   
1             NaN      0.0     6.0   2010.0        WD           Normal   
2            Gar2  12500.0     6.0   2010.0        WD           Normal   
3             NaN      0.0     4.0   2010.0        WD           Normal   
4             NaN      0.0     3.0   2010.0        WD           Normal   
...           ...      ...     ...      ...        ...             ...   
2925          NaN      0.0     3.0   2006.0        WD           Normal   
2926          NaN      0.0     6.0   2006.0        WD           Normal   
2927         Shed    700.0     7.0   2006.0        WD           Normal   
2928          NaN      0.0     4.0   2006.0        WD           Normal   
2929          NaN      0.0    11.0   2006.0        WD           Normal   

      SalePrice  
0      215000.0  
1      105000.0  
2      172000.0  
3      244000.0  
4      189900.0  
...         ...  
2925   142500.0  
2926   131000.0  
2927   132000.0  
2928   170000.0  
2929   188000.0  

[2930 rows x 80 columns]

In [15]:
si = SimpleImputer(strategy='most_frequent')
data[cat] = si.fit_transform(data[cat])

In [16]:
si

SimpleImputer(strategy='most_frequent')

In [17]:
data.isna().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [20]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [21]:
le = LabelEncoder()
ssc = StandardScaler()
for i in cat:
    data[i] = le.fit_transform(data[i])

In [22]:
data[num] = ssc.fit_transform(data[num])

In [23]:
data['Alley'].unique()

array([0, 1])

In [24]:
X = data.drop('Alley',axis=1)
y = data['Alley']

In [25]:
from sklearn.decomposition import PCA

In [26]:
pca = PCA(n_components=5)

In [27]:
X = pca.fit_transform(X)

In [28]:
X

array([[ 1.34845906, -5.08767676, -2.30246401, -3.4480072 , -0.60310454],
       [-0.20440381,  3.22071945,  4.41369552, -1.77990854,  0.47795103],
       [-0.06557197,  4.7431713 ,  1.71283857, -4.11495411,  1.64129884],
       ...,
       [-0.85059263,  0.16560269,  1.68743339,  0.30298844,  3.28256724],
       [ 0.28967661, -6.50391035, -1.61054562, -3.92448672,  1.51800822],
       [ 0.51373269, -5.46535545, -4.61249923,  2.50203769,  0.91880151]])

In [29]:
pd.DataFrame(X)

0         1         2         3         4
0     1.348459 -5.087677 -2.302464 -3.448007 -0.603105
1    -0.204404  3.220719  4.413696 -1.779909  0.477951
2    -0.065572  4.743171  1.712839 -4.114954  1.641299
3     2.228306 -9.582438 -5.281328 -2.559011 -1.678070
4    -6.733375  3.686007 -1.787158  0.729849  2.821425
...        ...       ...       ...       ...       ...
2925  0.127081 -6.874131 -0.117337  1.139934  3.440749
2926  0.145690 -6.864333 -0.165469 -3.459579  1.813588
2927 -0.850593  0.165603  1.687433  0.302988  3.282567
2928  0.289677 -6.503910 -1.610546 -3.924487  1.518008
2929  0.513733 -5.465355 -4.612499  2.502038  0.918802

[2930 rows x 5 columns]

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
lr = LogisticRegression()

In [34]:
lr.fit(X_train,y_train)

LogisticRegression()

In [35]:
y_pred = lr.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(y_test,y_pred)

0.9812286689419796

In [38]:
import pickle
with open("PCA_model.pkl", "wb") as file:
    pickle.dump(PCA, file)

print("✅ Model saved!")

✅ Model saved!
